# Generated by Django 5.0.4 on 2024-08-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='id_chat',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
