# Generated by Django 5.0.4 on 2024-05-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_slug_profile_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug_profile',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
