# Generated by Django 5.0.4 on 2024-05-20 02:12

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profile_slug_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default='default_profile.jpg', upload_to=main_app.models.image_file_path),
        ),
    ]
