# Generated by Django 5.0.4 on 2024-05-11 23:18

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=main_app.models.image_file_path),
        ),
    ]
