# Generated by Django 5.0.4 on 2024-05-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_post',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
